// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Exercise struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ExerciseSession struct {
	ID                uuid.UUID
	WorkoutSessionID  uuid.UUID
	WorkoutExerciseID uuid.UUID
	Completed         bool
	IsActive          bool
	EndedAt           sql.NullTime
	CreatedAt         time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	IsRevoked bool
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type SessionLog struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	WorkoutSessionID      uuid.UUID
	WorkoutExerciseLogsID uuid.NullUUID
	LogType               string
	LogPriority           string
	LogMessage            string
	CreatedAt             time.Time
}

type User struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	PasswordHash string
	Email        string
	Age          sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsPremium    bool
}

type Workout struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type WorkoutExercise struct {
	ID         uuid.UUID
	WorkoutID  uuid.UUID
	ExerciseID uuid.UUID
	Sets       int32
	RepsMin    int32
	RepsMax    int32
	Weight     float64
	Interval   int32
	Rest       int32
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type WorkoutExerciseLog struct {
	ID                uuid.UUID
	ExerciseSessionID uuid.UUID
	SetNumber         int32
	Reps              int32
	Weight            string
	IntervalSec       int32
	Notes             sql.NullString
	CreatedAt         time.Time
}

type WorkoutSession struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	WorkoutID uuid.UUID
	Completed bool
	IsActive  bool
	EndedAt   sql.NullTime
	CreatedAt time.Time
	ExpiresAt time.Time
}
