// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: exercises.sql

package services

import (
	"context"
)

const getExerciseNameByID = `-- name: GetExerciseNameByID :one
SELECT name
FROM exercises
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetExerciseNameByID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getExerciseNameByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
