// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package services

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Exercise struct {
	ID        int32
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ExerciseSession struct {
	ID                int32
	WorkoutSessionID  int32
	WorkoutExerciseID int32
	TotalSets         int32
	EndedAt           sql.NullTime
	CreatedAt         time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	IsRevoked bool
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type SessionLog struct {
	ID          int64
	UserID      uuid.UUID
	WorkoutID   int32
	ExerciseIds []string
	Logs        string
	LogType     string
	LogPriority string
	LogMessage  string
	Pr          sql.NullBool
	CreatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	PasswordHash string
	Email        string
	Age          sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsPremium    bool
}

type Workout struct {
	ID          int32
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type WorkoutExercise struct {
	ID         int32
	WorkoutID  int32
	ExerciseID int32
	Name       string
	Sets       int32
	RepsMin    int32
	RepsMax    int32
	Weight     float64
	Interval   int32
	Rest       int32
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type WorkoutSession struct {
	ID             int32
	UserID         uuid.UUID
	WorkoutID      int32
	TotalExercises int32
	EndedAt        sql.NullTime
	CreatedAt      time.Time
	ExpiresAt      time.Time
}
